apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../phase2
  - postgres.yaml
  - redis.yaml
  - worker.yaml
  - network-policies.yaml
patches:
  - path: configmap-patch.yaml
  - path: api-patch.yaml
