apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-shop-gateway
  namespace: shop
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: ["api", "web"]
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
          podSelector:
            matchLabels:
              gateway.envoyproxy.io/owning-gateway-namespace: shop
              gateway.envoyproxy.io/owning-gateway-name: shop
      ports:
        - {protocol: TCP, port: 8000}
        - {protocol: TCP, port: 8080}
