# Demonstration data only. This is not the application's runtime Secret.
apiVersion: v1
kind: Secret
metadata:
    name: shop-demo
    namespace: shop
type: Opaque
stringData:
    DEMO_PASSWORD: ENC[AES256_GCM,data:fI+Z44I1XluGOYhtArdzSBZvVw==,iv:JkV/7vYUSo1b4G7FcBRpobBH5b4PZnmzBmh4APo/QGk=,tag:mzUY1whmExpU8DvlBRWlrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUzR6ejM0eExqRHdXcE5O
            VUFtUjNFSzRTUDlaS0lTcTFtdEFsV3JCYzJFClFZdTgrK1ZiL3Uvcno2aFg0NUlO
            a3NqWjhIY0M5YzFGR29SNVJqdXpqM28KLS0tIEJSZlpTaWRGYlRHWnFlYnNOekZ4
            Um1Vd0NMcFh4TFJKdjZtMDZSNkw0MU0KjvTF/zsicRy4WCGN0fk5/KyAnj2FodEh
            hjqeLPm1KFCgzFPBJGX7MHrPQjIsC1fIt2V6/RHnCxBL5Cpn92IewQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yyekyt3u5tczl2trmhnsauyh2hdreer77hzmmkrul95xgjkaaf2skdzr26
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T19:24:48Z"
    mac: ENC[AES256_GCM,data:Zl2jDUe8LVgl/2yJFGLPsokPMtFLEepY1hcZiDsZyGBroOrwQDaCpaRnvPngLROE2uVjpLa87ppmj2qOwuxQGjRBMeziXJolYqmVKq+5l+jlWeDUiLp8bS4dqD30SH/9N5340LOXorQH0sEzY1MOf3gtKbHdIcDDKKfkiq37PMo=,iv:ch5wsS1cGrEp9ilgJMWBn1VxKrUeSyXDHhz+aPJhy1E=,tag:CxCE1Lh/LsYQCPf0fpAG5w==,type:str]
    version: 3.13.3
