apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../phase7/dev
# Source commit: 13fff5e0a56a440435d7a59a814455e78165ca2d
images:
  - name: kube-foundry-api
    newName: ghcr.io/chriswayneh/kube-foundry-api
    digest: sha256:968b131dcf0f58103d4b65a813212ef7635cde3a0a1e2ad3bfb1d296aa0beae2
  - name: kube-foundry-worker
    newName: ghcr.io/chriswayneh/kube-foundry-worker
    digest: sha256:822ebc25d5d125ceb81875212cd7cc5f9f5613b4e26914ee6d940e7b552ae7cd
  - name: kube-foundry-web
    newName: ghcr.io/chriswayneh/kube-foundry-web
    digest: sha256:c8393b44991ff30265d7573fb80da313537ef3e629b00f81c9002ec929c6b44a
