apiVersion: v1
data:
  APP_CONFIGURED: "true"
  DEPENDENCY_CHECKS_ENABLED: "true"
  LOG_LEVEL: INFO
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: shop
    app.kubernetes.io/part-of: kube-foundry
  name: shop-config
  namespace: {{ .Release.Namespace }}
