apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: shop
    app.kubernetes.io/part-of: kube-foundry
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: shop
